services:
  - type: web
    name: yt-whisper-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
